public class SpringCMDocumentOffloadHandlerTest {
 
    
    
/*
 * https://developer.salesforce.com/blogs/developer-relations/2013/03/testing-apex-callouts-using-httpcalloutmock.html

@isTest
public class CalloutAccountsTest{
	public static testmethod void testAccountCallout() {
        SingleRequestMock fakeResponse = new SingleRequestMock(200,
                                                 'Complete',
                                                 '[{"Name": "sForceTest1"}]',
                                                 null);
		Test.setMock(HttpCalloutMock.class, fakeResponse);
        CalloutAccounts.getAccounts();
      
    }
}


*/

}